### ISSUE TITLE
[Testing] Fix segfault in helper function

### ISSUE THREAD

**Issue by 3vilcookie** [3vilcookie/femto#15]
## Problem

When testing femto via `make unittest` on Fedora 31 (Thirty One) with kernel 5.5.8-200.fc31.x86_64 it crashes on `test_valid_cursor_circle () at test/cursor_test.c:189`.

<details>
<summary>Output of the crash</summary>

```
$ bin/femto_test 
BuildDate: Tue 07 Apr 2020 10:56:09 AM UTC
BuildVersion: c797375
---- Session ----
it loads a file                                                                                         OK
it loads a file with long lines                                                                         OK
it saves a file                                                                                         OK
it inits a session                                                                                      OK
---- Terminal ----
it enables and disables raw mode without an error                                                       OK
it gets terminal size without an error                                                                  OK
it gets the cursor position without an error                                                            OK
---- Buffer ----
it creates a buffer                                                                                     OK
it appends to a buffer                                                                                  SKIP
it appends to a buffer multiple times                                                                   SKIP
---- Helper ----
it can find the minimum                                                                                 OK
it can find the maximum                                                                                 OK
it can clamp too high number                                                                            OK
it can clamp if range is inverted                                                                       OK
it can clamp valid                                                                                      OK
---- Cursor ----
---- Valid moves ----
it moves cursor downwards. ts:2/2, lc:2, off:0/0, p:1/1 -> py:2                                         OK
it moves cursor upwards. ts:2/2, lc:2, off:0/0, p:1/2 -> py:1                                           OK
it moves cursor left. ts:3/1, lc:1, off:0/0, p:2/1 -> px:1                                              OK
it moves cursor right. ts:3/1, lc:1, off:0/0, p:2/1 -> px:3                                             OK
femto_test: malloc.c:2379: sysmalloc: Assertion `(old_top == initial_top (av) && old_size == 0) || ((unsigned long) (old_size) >= MINSIZE && prev_inuse (old_top) && ((unsigned long) old_end & (pagesize - 1)) == 0)' failed.
^[[13;1RAborted (core dumped)
```
</details>

## Investigation

<details>
<summary>gdb output</summary>

```
$ gdb bin/femto_test 
GNU gdb (GDB) Fedora 8.3.50.20190824-30.fc31
Copyright (C) 2019 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-redhat-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from bin/femto_test...
(gdb) r
Starting program: /home/rpour/dev/femto/bin/femto_test 
Missing separate debuginfos, use: dnf debuginfo-install glibc-2.30-11.fc31.x86_64
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
BuildDate: Tue 07 Apr 2020 10:56:09 AM UTC
BuildVersion: c797375
---- Session ----
it loads a file                                                                                         OK
it loads a file with long lines                                                                         OK
it saves a file                                                                                         OK
it inits a session                                                                                      OK
---- Terminal ----
it enables and disables raw mode without an error                                                       OK
it gets terminal size without an error                                                                  OK
it gets the cursor position without an error                                                            OK
---- Buffer ----
it creates a buffer                                                                                     OK
it appends to a buffer                                                                                  SKIP
it appends to a buffer multiple times                                                                   SKIP
---- Helper ----
it can find the minimum                                                                                 OK
it can find the maximum                                                                                 OK
it can clamp too high number                                                                            OK
it can clamp if range is inverted                                                                       OK
it can clamp valid                                                                                      OK
---- Cursor ----
---- Valid moves ----
it moves cursor downwards. ts:2/2, lc:2, off:0/0, p:1/1 -> py:2                                         OK
it moves cursor upwards. ts:2/2, lc:2, off:0/0, p:1/2 -> py:1                                           OK
it moves cursor left. ts:3/1, lc:1, off:0/0, p:2/1 -> px:1                                              OK
it moves cursor right. ts:3/1, lc:1, off:0/0, p:2/1 -> px:3                                             OK
femto_test: malloc.c:2379: sysmalloc: Assertion `(old_top == initial_top (av) && old_size == 0) || ((unsigned long) (old_size) >= MINSIZE && prev_inuse (old_top) && ((unsigned long) old_end & (pagesize - 1)) == 0)' failed.

Program received signal SIGABRT, Aborted.
0x00007ffff7cb1625 in raise () from /lib64/libc.so.6
(gdb) ;1Rbt
Undefined command: "".  Try "help".
(gdb) bt
#0  0x00007ffff7cb1625 in raise () from /lib64/libc.so.6
#1  0x00007ffff7c9a8d9 in abort () from /lib64/libc.so.6
#2  0x00007ffff7cfca7a in __malloc_assert () from /lib64/libc.so.6
#3  0x00007ffff7cff2bf in sysmalloc () from /lib64/libc.so.6
#4  0x00007ffff7d00072 in _int_malloc () from /lib64/libc.so.6
#5  0x00007ffff7d01f55 in calloc () from /lib64/libc.so.6
#6  0x0000000000403a1e in create_session_perfect_fit_by_input (line_count=2, lines=0x7fffffffdbc0) at test/cursor_test.c:23
#7  0x0000000000403f0f in test_valid_cursor_circle () at test/cursor_test.c:189
#8  0x00000000004045bc in test_suite_cursor () at test/cursor_test.c:439
#9  0x00000000004046af in main (argc=1, argv=0x7fffffffdcf8) at test/femto_test.c:31
```
</details>

<details>
<summary>valgrind output</summary>

```
$ valgrind bin/femto_test 
==4139705== Memcheck, a memory error detector
==4139705== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==4139705== Using Valgrind-3.15.0 and LibVEX; rerun with -h for copyright info
==4139705== Command: bin/femto_test
==4139705== 
BuildDate: Tue 07 Apr 2020 10:56:09 AM UTC
BuildVersion: c797375
---- Session ----
it loads a file                                                                                         OK
it loads a file with long lines                                                                         OK
it saves a file                                                                                         OK
it inits a session                                                                                      OK
---- Terminal ----
it enables and disables raw mode without an error                                                       OK
it gets terminal size without an error                                                                  OK
it gets the cursor position without an error                                                            OK
---- Buffer ----
it creates a buffer                                                                                     OK
it appends to a buffer                                                                                  SKIP
it appends to a buffer multiple times                                                                   SKIP
---- Helper ----
it can find the minimum                                                                                 OK
it can find the maximum                                                                                 OK
it can clamp too high number                                                                            OK
it can clamp if range is inverted                                                                       OK
it can clamp valid                                                                                      OK
---- Cursor ----
---- Valid moves ----
==4139705== Invalid write of size 8
==4139705==    at 0x403B2E: create_session_perfect_fit_by_input (cursor_test.c:33)
==4139705==    by 0x403C3A: test_valid_cursor_down_movement (cursor_test.c:92)
==4139705==    by 0x404593: test_suite_cursor (cursor_test.c:435)
==4139705==    by 0x4046AE: main (femto_test.c:31)
==4139705==  Address 0x4bd55c0 is 0 bytes after a block of size 16 alloc'd
==4139705==    at 0x483BB1A: calloc (vg_replace_malloc.c:762)
==4139705==    by 0x403A1D: create_session_perfect_fit_by_input (cursor_test.c:23)
==4139705==    by 0x403C3A: test_valid_cursor_down_movement (cursor_test.c:92)
==4139705==    by 0x404593: test_suite_cursor (cursor_test.c:435)
==4139705==    by 0x4046AE: main (femto_test.c:31)
==4139705== 
==4139705== Invalid write of size 8
==4139705==    at 0x403A92: create_session_perfect_fit_by_input (cursor_test.c:29)
==4139705==    by 0x403C3A: test_valid_cursor_down_movement (cursor_test.c:92)
==4139705==    by 0x404593: test_suite_cursor (cursor_test.c:435)
==4139705==    by 0x4046AE: main (femto_test.c:31)
==4139705==  Address 0x4bd55d0 is 16 bytes after a block of size 16 alloc'd
==4139705==    at 0x483BB1A: calloc (vg_replace_malloc.c:762)
==4139705==    by 0x403A1D: create_session_perfect_fit_by_input (cursor_test.c:23)
==4139705==    by 0x403C3A: test_valid_cursor_down_movement (cursor_test.c:92)
==4139705==    by 0x404593: test_suite_cursor (cursor_test.c:435)
==4139705==    by 0x4046AE: main (femto_test.c:31)
==4139705== 
==4139705== Invalid read of size 8
==4139705==    at 0x403AD1: create_session_perfect_fit_by_input (cursor_test.c:30)
==4139705==    by 0x403C3A: test_valid_cursor_down_movement (cursor_test.c:92)
==4139705==    by 0x404593: test_suite_cursor (cursor_test.c:435)
==4139705==    by 0x4046AE: main (femto_test.c:31)
==4139705==  Address 0x4bd55d0 is 16 bytes after a block of size 16 alloc'd
==4139705==    at 0x483BB1A: calloc (vg_replace_malloc.c:762)
==4139705==    by 0x403A1D: create_session_perfect_fit_by_input (cursor_test.c:23)
==4139705==    by 0x403C3A: test_valid_cursor_down_movement (cursor_test.c:92)
==4139705==    by 0x404593: test_suite_cursor (cursor_test.c:435)
==4139705==    by 0x4046AE: main (femto_test.c:31)
==4139705== 
==4139705== Invalid write of size 8
==4139705==    at 0x403B07: create_session_perfect_fit_by_input (cursor_test.c:32)
==4139705==    by 0x403C3A: test_valid_cursor_down_movement (cursor_test.c:92)
==4139705==    by 0x404593: test_suite_cursor (cursor_test.c:435)
==4139705==    by 0x4046AE: main (femto_test.c:31)
==4139705==  Address 0x4bd55c8 is 8 bytes after a block of size 16 alloc'd
==4139705==    at 0x483BB1A: calloc (vg_replace_malloc.c:762)
==4139705==    by 0x403A1D: create_session_perfect_fit_by_input (cursor_test.c:23)
==4139705==    by 0x403C3A: test_valid_cursor_down_movement (cursor_test.c:92)
==4139705==    by 0x404593: test_suite_cursor (cursor_test.c:435)
==4139705==    by 0x4046AE: main (femto_test.c:31)
==4139705== 
==4139705== Invalid read of size 8
==4139705==    at 0x4026C2: fe_move_cursor (session.c:226)
==4139705==    by 0x402A48: fe_move (session.c:295)
==4139705==    by 0x403C85: test_valid_cursor_down_movement (cursor_test.c:100)
==4139705==    by 0x404593: test_suite_cursor (cursor_test.c:435)
==4139705==    by 0x4046AE: main (femto_test.c:31)
==4139705==  Address 0x4bd55c8 is 8 bytes after a block of size 16 alloc'd
==4139705==    at 0x483BB1A: calloc (vg_replace_malloc.c:762)
==4139705==    by 0x403A1D: create_session_perfect_fit_by_input (cursor_test.c:23)
==4139705==    by 0x403C3A: test_valid_cursor_down_movement (cursor_test.c:92)
==4139705==    by 0x404593: test_suite_cursor (cursor_test.c:435)
==4139705==    by 0x4046AE: main (femto_test.c:31)
==4139705== 
==4139705== Invalid read of size 8
==4139705==    at 0x4026C5: fe_move_cursor (session.c:226)
==4139705==    by 0x402A48: fe_move (session.c:295)
==4139705==    by 0x403C85: test_valid_cursor_down_movement (cursor_test.c:100)
==4139705==    by 0x404593: test_suite_cursor (cursor_test.c:435)
==4139705==    by 0x4046AE: main (femto_test.c:31)
==4139705==  Address 0x4bd55d0 is 16 bytes after a block of size 16 alloc'd
==4139705==    at 0x483BB1A: calloc (vg_replace_malloc.c:762)
==4139705==    by 0x403A1D: create_session_perfect_fit_by_input (cursor_test.c:23)
==4139705==    by 0x403C3A: test_valid_cursor_down_movement (cursor_test.c:92)
==4139705==    by 0x404593: test_suite_cursor (cursor_test.c:435)
==4139705==    by 0x4046AE: main (femto_test.c:31)
==4139705== 

valgrind: m_mallocfree.c:305 (get_bszB_as_is): Assertion 'bszB_lo == bszB_hi' failed.
valgrind: Heap block lo/hi size mismatch: lo = 80, hi = 1.
This is probably caused by your program erroneously writing past the
end of a heap block and corrupting heap metadata.  If you fix any
invalid writes reported by Memcheck, this assertion failure will
probably go away.  Please try that before reporting this as a bug.


host stacktrace:
==4139705==    at 0x58046FCA: ??? (in /usr/libexec/valgrind/memcheck-amd64-linux)
==4139705==    by 0x580470F7: ??? (in /usr/libexec/valgrind/memcheck-amd64-linux)
==4139705==    by 0x5804729B: ??? (in /usr/libexec/valgrind/memcheck-amd64-linux)
==4139705==    by 0x58051424: ??? (in /usr/libexec/valgrind/memcheck-amd64-linux)
==4139705==    by 0x5803DE6A: ??? (in /usr/libexec/valgrind/memcheck-amd64-linux)
==4139705==    by 0x5803CD6F: ??? (in /usr/libexec/valgrind/memcheck-amd64-linux)
==4139705==    by 0x58041ED4: ??? (in /usr/libexec/valgrind/memcheck-amd64-linux)
==4139705==    by 0x5803C1A8: ??? (in /usr/libexec/valgrind/memcheck-amd64-linux)
==4139705==    by 0x58017AF4: ??? (in /usr/libexec/valgrind/memcheck-amd64-linux)
==4139705==    by 0x1002D9CFA1: ???
==4139705==    by 0x1002BA5F2F: ???
==4139705==    by 0x1002BA5F17: ???
==4139705==    by 0x1002BA5F2F: ???
==4139705==    by 0x1002BA5F3F: ???

sched status:
  running_tid=1

Thread 1: status = VgTs_Runnable (lwpid 4139705)
==4139705==    at 0x4026D1: fe_move_cursor (session.c:226)
==4139705==    by 0x402A48: fe_move (session.c:295)
==4139705==    by 0x403C85: test_valid_cursor_down_movement (cursor_test.c:100)
==4139705==    by 0x404593: test_suite_cursor (cursor_test.c:435)
==4139705==    by 0x4046AE: main (femto_test.c:31)
client stack range: [0x1FFEFFD000 0x1FFF000FFF] client SP: 0x1FFEFFFB00
valgrind stack range: [0x1002AA6000 0x1002BA5FFF] top usage: 7464 of 1048576


Note: see also the FAQ in the source distribution.
It contains workarounds to several common problems.
In particular, if Valgrind aborted or crashed after
identifying problems in your program, there's a good chance
that fixing those problems will prevent Valgrind aborting or
crashing, especially if it happened in m_mallocfree.c.

If that doesn't help, please report this bug to: www.valgrind.org

In the bug report, send all the above text, the valgrind
version, and what OS and version you are using.  Thanks.
```
</details>

**Comment by 3vilcookie** [comment]
Closed with PR #11
